[workspace]
members = ["flt2vhs", "vhscat", "convert-all-flts", "logsetup", "patch-bms-novhs"]
resolver = "2" # Try new dependency resolver from Rust 1.51

[profile.dev]
opt-level = 3 # We want debug builds be optimized + debug to benchmark them
incremental = true # Iterate faster
