on: [push, pull_request]

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        continue-on-error: true # WARNING: only for this example, remove it!
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        continue-on-error: true # WARNING: only for this example, remove it!
        with:
          command: clippy
          args: -- -D warnings

  build-cross:
    name: Builds via cross-compiling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install mingw
        run: sudo apt-get install mingw-w64

      - name: Build generic win32 binary
        env:
          RUSTFLAGS: -C target-cpu=generic
        run: |
          rustup target add x86_64-pc-windows-gnu
          cargo build --target x86_64-pc-windows-gnu

  build-windows:
    name: Builds natively on windows
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build generic win32 binary
        env:
          RUSTFLAGS: -C target-cpu=generic
        run: |
          rustup target add x86_64-pc-windows-msvc
          cargo build --target x86_64-pc-windows-msvc
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: MSVC Executables
          path: |
            x86_64-pc-windows-msvc/debug/*.exe
            x86_64-pc-windows-msvc/debug/*.pdb
          if-no-files-found: warn
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # uncomment below to enable debugging!
      - name: Setup tmate
        uses: mxschmitt/action-tmate@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
